### ISSUE TITLE
No visible circle when typing password

### ISSUE THREAD

**Issue by ivankovnatsky** [swaywm/swaylock#176] opened 2021-04-28 07:19 UTC
Running swaylock without any arguments, all white screen, typing passwords -- unlocks without the problem, but the circle is not visible as before.

Do I miss something?

running NixOS Unstable.

**Comment by emersion** [comment] 2021-04-28 07:22
Seems like a duplicate of https://github.com/swaywm/swaylock/issues/168?

**Closed** 2021-04-28 07:24 UTC
