### ISSUE TITLE
Can't start swaylock on lidclose

### ISSUE THREAD

**Issue by kflak** [swaywm/swaylock#41] opened 2019-02-02 13:22 UTC
Trying to replicate the behavior from i3lock with the following systemd service:
```
[Unit]
Description=Lock screen on resume from suspend
Before=sleep.target

[Service]
User=kf
Environment=DISPLAY=:0
Type=forking
ExecStart=/usr/bin/swaylock
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sleep.target
```
but it is not running... the exact same service runs fine with i3lock. 
Output from journalctl:
```
Feb 02 15:13:48 arch systemd-logind[3378]: Lid closed.
Feb 02 15:13:48 arch systemd-logind[3378]: Suspending...
Feb 02 15:13:48 arch systemd[1]: Starting Lock screen on resume from suspend...
-- Subject: A start job for unit lock.service has begun execution
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit lock.service has begun execution.
-- 
-- The job identifier is 1703.
Feb 02 15:13:48 arch swaylock[16317]: error: XDG_RUNTIME_DIR not set in the environment.
Feb 02 15:13:48 arch swaylock[16317]: 2019-02-02 15:13:48 - [swaylock/main.c:1047] Unable to connect to the compositor. If your compositor is running, check or set the WAYLAND_DISPLAY enviro>
Feb 02 15:13:48 arch systemd[1]: lock.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- An ExecStart= process belonging to unit lock.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Feb 02 15:13:49 arch systemd[1]: lock.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit lock.service has entered the 'failed' state with result 'exit-code'.
Feb 02 15:13:49 arch systemd[1]: Failed to start Lock screen on resume from suspend.
-- Subject: A start job for unit lock.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit lock.service has finished with a failure.
-- 
-- The job identifier is 1703 and the job result is failed.
Feb 02 15:13:49 arch systemd[1]: Reached target Sleep.
-- Subject: A start job for unit sleep.target has finished successfully
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit sleep.target has finished successfully.
-- 
-- The job identifier is 1649.
Feb 02 15:13:49 arch systemd[1]: Starting Suspend...
-- Subject: A start job for unit systemd-suspend.service has begun execution
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit systemd-suspend.service has begun execution.
-- 
-- The job identifier is 1646.
Feb 02 15:13:49 arch systemd-sleep[16320]: Suspending system...
-- Subject: System sleep state suspend entered
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The system has now entered the suspend sleep state.
```
System Arch Linux 4.14.71-rt44-1-rt-lts, sway version 1.0-beta.2-204-g70637b40 (Jan 17 2019, branch 'master'), swaylock version 1.2-46-geffdea5 (Feb  1 2019, branch 'master')

Am I just messing up the systemd service file, or is there a bug somewhere?

**Comment by bendooru** [comment] 2019-02-02 16:03
I think you have to set `WAYLAND_DISPLAY`, not `DISPLAY`. In my case, it would be

    Environment=WAYLAND_DISPLAY=wayland-0

**Comment by mnussbaum** [comment] 2019-02-02 23:51
Swaylock likely needs access to the `SWAYSOCK` env var which is only available to processes started within sway itself. To work around this you might be able to add the following to your sway config:

```
exec systemctl import-environment SWAYSOCK
```

That way after sway is running the socket env var will be available to your systemd units

**Comment by kflak** [comment] 2019-02-03 07:56
Thanks for the help! But so far no joy, unfortunately. As I mentioned, i3lock works fine without fiddling with SWAYSOCK or WAYLAND_DISPLAY variables, as does physlock. I'm a bit at a loss on how to debug this further...

**Comment by emersion** [comment] 2019-02-03 09:58
>As I mentioned, i3lock works fine without fiddling with SWAYSOCK or WAYLAND_DISPLAY variables, as does physlock.

You do need to set DISPLAY though (which selects the X11 display to use), it's the same on Wayland, you need to set WAYLAND_DISPLAY.

Related: https://github.com/swaywm/sway/issues/2639

**Comment by kflak** [comment] 2019-02-03 10:46
Thanks for your patience... So, now my full systemd file looks like this:
```
[Unit]
Description=Lock screen on resume from suspend
Before=sleep.target

[Service]
User=kf
Environment=WAYLAND_DISPLAY=wayland-0
Environment=XDG_RUNTIME_DIR=/tmp
Type=forking
ExecStart=/usr/bin/swaylock --image="/home/kf/Pictures/wallpaper/IMG_4989.png" 
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sleep.target
```
... and the lock still doesn't happen...

**Comment by emersion** [comment] 2019-02-03 10:53
What is `journalctl` saying?

**Comment by kflak** [comment] 2019-02-03 11:54
Still an issue with the WAYLAND_DISPLAY environment variable, it seems... 
Output from journalct:
```
Feb 03 13:46:36 arch systemd[1]: Starting Lock screen on resume from suspend...
-- Subject: A start job for unit lock.service has begun execution
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit lock.service has begun execution.
-- 
-- The job identifier is 6111.
Feb 03 13:46:37 arch swaylock[18808]: 2019-02-03 13:46:37 - [swaylock/main.c:1047] Unable to connect to the compositor. If your compositor is running, check or set the WAYLAND_DISPLAY environment variable.
Feb 03 13:46:37 arch systemd[1]: lock.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- An ExecStart= process belonging to unit lock.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Feb 03 13:46:37 arch systemd[1]: lock.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit lock.service has entered the 'failed' state with result 'exit-code'.
Feb 03 13:46:37 arch systemd[1]: Failed to start Lock screen on resume from suspend.
-- Subject: A start job for unit lock.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit lock.service has finished with a failure.
-- 
-- The job identifier is 6111 and the job result is failed.
```

**Comment by kflak** [comment] 2019-02-03 11:57
Output from `echo $WAYLAND_DISPLAY` is `wayland-0` still...

**Comment by emersion** [comment] 2019-02-04 08:35
I think you need to have the same `$XDG_RUNTIME_DIR` as the compositor (so setting `/tmp` won't work), because the Wayland socket will be there.

**Comment by gdamjan** [comment] 2019-02-10 15:58
the `sleep.target` is a system systemd target, and it's wrong to use that for user sessions.

just use `swayidle` and you can find a user .service file in the wiki
https://github.com/swaywm/sway/wiki/Systemd-integration

**Comment by kflak** [comment] 2019-02-11 09:59
@gdamjan Thanks a lot for that! It solves my problem elegantly :-) However, one issue that I can't seem to get around is that on opening the lid the screen is visible for a second or so before the lock kicks in. I used to be able to solve that by adding `ExecStartPost=/usr/bin/sleep 1` to the service, but this seems to have no effect in this case. Am I missing anything obvious here?

**Comment by gdamjan** [comment] 2019-02-11 10:15
make sure you use -w in swayidle, AND -f in swaylock

**Comment by kflak** [comment] 2019-02-11 10:25
Ah, my bad... the service didn't reload properly. Now it works! Thanks a lot for taking the time to point me in the right direction!

**Comment by kflak** [comment] 2019-02-16 14:21
Sorry to keep badgering, but I am still occasionally getting the behavior where swaylock doesn't kick in for a couple of seconds after I open the lid of the laptop. The weird thing is that it's not consistent, it only happens once in a while. I have set up the service according to the wiki, with the addition of  a sleep 1 command, as recommended in the Arch wiki. My service file now looks like this:
```
[Unit]
Description=Idle manager for Wayland
Documentation=man:swayidle(1)
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/swayidle -w \
        timeout 300 'swaylock -f --indicator-radius 200 -c 000000' \
        timeout 600 'swaymsg "output * dpms off"' \
                resume 'swaymsg "output * dpms on"' \
        before-sleep 'swaylock -f --indicator-radius 200 -c 000000'
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sway-session.target
```

**Comment by luispabon** [comment] 2019-06-03 09:33
I'm getting the same issue but with lock and idle run on sway startup:

```
set $lock_bg ~/Pictures/backgrounds/galen-crout-175291.jpg

bindsym Alt+l exec swaylock -i $lock_bg

exec swayidle -w \
         timeout 300 'swaylock -f -c 000000' -i $lock_bg \
         timeout 600 'swaymsg "output * dpms off"' \
              resume 'swaymsg "output * dpms on"' \
         before-sleep 'swaylock -f -c 000000 -i $lock_bg'
```

**Comment by luispabon** [comment] 2019-06-07 14:08
It feels like `before-sleep` is taking too long and doesn't actually finish executing swaylock before the computer initiates suspend.

**Comment by gustavoheinz** [comment] 2019-10-04 01:45
Getting the same bug here.

I can reproduce the bug if I set an image with the `-i` parameter, if I set only a color it always works properly.

**Comment by kgizdov** [comment] 2020-01-25 21:31
for me swaylock crashes with `unrecognised option '--image /home/..../background.jpg'` and then the log clearly shows the `--image` option is a valid option. Is this a argument parsing thing?

**Comment by gdamjan** [comment] 2020-01-28 17:36
the before-sleep issue should be tracked in swayidle

**Comment by brainrape** [comment] 2020-04-05 12:04
Looks like it was a bug in swayidle.
https://github.com/swaywm/sway/pull/3381
You can probably close this issue.

**Closed** 2020-04-05 12:14 UTC
