### ISSUE TITLE
Feature: option for automatic unlock if input within short time after lock

### ISSUE THREAD

**Issue by Kilobyte22** [swaywm/swaylock#193] opened 2021-06-16 18:51 UTC
I propose an option that, when enabled, starts a timeout when swaylock starts up. If the user performs any input during that timeout, swaylock automatically unlocks.

Usecase: when an automatic screen lock is used, this can be handy in case the screen locks without the user wanting it. This is consitent with most desktop environments and mobile phones: A manual lock issued by a user is effective immediately, a lock issued by autolock takes a couple of seconds (usually 5) to become effective.

**Comment by emersion** [comment] 2021-06-16 19:11
Duplicate of https://github.com/swaywm/swaylock/issues/50

**Closed by emersion** 2021-06-16 19:11 UTC

**Comment by Kilobyte22** [comment] 2021-06-18 18:56
I tried to find if that had been suggested, but didn't see it. Sorry.
