### ISSUE TITLE
no password pass

### ISSUE THREAD

**Issue by Simao-pp-C** [swaywm/swaylock#309] opened 2023-08-13 20:22 UTC
i´m using archt and when i lock screen it just unlock whit any key 
the version intaled is 6f67d76 10 jul 2023

**Comment by kennylevinsen** [comment] 2023-08-14 07:41
There's a chance that it's your PAM stack (/etc/pam.d/swaylock or one of its includes) that is misconfigured, with a module that is letting you pass.

If it's a swaylock bug, try running swaylock like this to collect a log: `WAYLAND_DEBUG=1 swaylock 2>swaylock.log`. Note that this log will contain all your keypresses, so do not type anything sensitive in this test.

**Comment by Simao-pp-C** [comment] 2023-08-17 18:43
hi, this repeat a lot of times
wl_display@1.delete_id(20)
[2703451.275] wl_callback@20.done(13373473)
[2703451.289]  -> wl_surface@16.frame(new id wl_callback@20)
[2703451.302]  -> wl_subsurface@18.set_position(465, 164)
[2703451.314]  -> wl_surface@17.attach(nil, 0, 0)
[2703451.325]  -> wl_surface@17.commit()
[2703452.924]  -> wl_surface@17.set_buffer_scale(1)
[2703452.938]  -> wl_surface@17.attach(wl_buffer@22, 0, 0)
[2703452.950]  -> wl_surface@17.damage_buffer(0, 0, 2147483647, 2147483647)
[2703452.961]  -> wl_surface@17.commit()
[2703452.971]  -> wl_surface@16.commit()
[2703454.246] wl_buffer@22.release()

and

[2703033.263]  -> wl_display@1.sync(new id wl_callback@20)
[2703033.310] wl_display@1.delete_id(20)
[2703033.321] wl_callback@20.done(6869)

not sure what i´m looking for

**Comment by kennylevinsen** [comment] 2023-08-18 09:13
Attach the full log.

**Comment by Simao-pp-C** [comment] 2023-08-18 11:04
[swaylock.log](https://github.com/swaywm/swaylock/files/12378572/swaylock.log)

**Comment by kennylevinsen** [comment] 2023-08-18 11:24
The lock is not using ext_session_lock, so whatever you are running is either:
1. Older than v1.6 (that is, over a year old). If so, upgrade to the latest release and try again.
2. Not swaylock, but a fork. If so, report the issue to the maintainer of the fork instead of here.

Closing for now. You can reopen if the issue is observed with the latest swaylock release.

**Closed by kennylevinsen** 2023-08-18 11:24 UTC
