### ISSUE TITLE
Sometimes swaylock briefly shows the screen's content before unlocking

### ISSUE THREAD

**Issue by yory8** [swaywm/swaylock#118] opened 2019-12-10 20:16 UTC
Swaylock 1.3
Using swaylock from swayidle. 

The unlocked screen will briefly be visible before unlocking when resuming from suspend, very rarely and seemingly randomly.

**Comment by emersion** [comment] 2019-12-10 20:36
Duplicate of https://github.com/swaywm/swaylock/issues/99

**Closed by emersion** 2019-12-10 20:36 UTC
