### ISSUE TITLE
difference to i3lock: taking input

### ISSUE THREAD

**Issue by cherti** [swaywm/swaylock#161] opened 2020-12-31 17:19 UTC
`swaylock` differs in behavior from its equivalent `i3lock` when taking password input for unlocking:

When an incorrect password was entered, both swaylock as well as i3lock show a blue "verifying" and a red "wrong" circle. However, while i3 already reads input at that point for the next password, such that in case of an obvious typo one can already refill the password buffer (even though one has to wait with sending until the "wrong"-circle is through), swaylock seems to only take new password input after the wrong-bubble is gone, being unintuitive when coming from i3lock, as this is behavior not indicated anywhere, hence making it difficult to unlock the screen with swaylock when used to i3lock until one experimentally notices this key difference.

**Comment by emersion** [comment] 2021-06-08 08:18
Duplicate of https://github.com/swaywm/swaylock/issues/66

**Closed by emersion** 2021-06-08 08:18 UTC
