### ISSUE TITLE
Crash (and thus no unlocking needed) after turning monitors back on

### ISSUE THREAD

**Issue by e00E** [swaywm/swaylock#202] opened 2021-07-30 07:16 UTC
I inconsistently come back to an unlocked session after leaving the computer for several hours. System logs show that swaylock crashed.

```
> gdb /usr/bin/swaylock coredump
Reading symbols from /usr/bin/swaylock...
(No debugging symbols found in /usr/bin/swaylock)

warning: Can't open file /run/user/1000/sway-client-o6e2w3 (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/wlroots-KPGFLO (deleted) during file-backed mapping note processing

warning: Can't open file /run/user/1000/sway-client-EdMO3P (deleted) during file-backed mapping note processing

warning: Can't open file /run/user/1000/sway-client-vKxVQp (deleted) during file-backed mapping note processing
[New LWP 161378]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `swaylock -f -c 000000'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f39d16add22 in raise () from /usr/lib/libc.so.6
(gdb) where
#0  0x00007f39d16add22 in raise () at /usr/lib/libc.so.6
#1  0x00007f39d1697862 in abort () at /usr/lib/libc.so.6
#2  0x00007f39d16efd28 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007f39d16f792a in  () at /usr/lib/libc.so.6
#4  0x00007f39d16f89cc in malloc_consolidate () at /usr/lib/libc.so.6
#5  0x00007f39d16fa88b in _int_malloc () at /usr/lib/libc.so.6
#6  0x00007f39d16fd175 in calloc () at /usr/lib/libc.so.6
#7  0x00007f39d187e6cd in  () at /usr/lib/libxkbcommon.so.0
#8  0x00007f39d1880274 in xkb_keymap_new_from_buffer () at /usr/lib/libxkbcommon.so.0
#9  0x000055f1eaf9b05d in  ()
#10 0x00007f39d0d2dacd in  () at /usr/lib/libffi.so.7
#11 0x00007f39d0d2d03a in  () at /usr/lib/libffi.so.7
#12 0x00007f39d185afe4 in  () at /usr/lib/libwayland-client.so.0
#13 0x00007f39d1857563 in  () at /usr/lib/libwayland-client.so.0
#14 0x00007f39d1858cac in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#15 0x00007f39d18591e0 in wl_display_roundtrip_queue () at /usr/lib/libwayland-client.so.0
#16 0x00007f39d0d2dacd in  () at /usr/lib/libffi.so.7
#17 0x00007f39d0d2d03a in  () at /usr/lib/libffi.so.7
#18 0x00007f39d185afe4 in  () at /usr/lib/libwayland-client.so.0
#19 0x00007f39d1857563 in  () at /usr/lib/libwayland-client.so.0
#20 0x00007f39d1858cac in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#21 0x000055f1eaf981c1 in  ()
#22 0x000055f1eaf97faf in  ()
#23 0x000055f1eaf965ff in  ()
#24 0x00007f39d1698b25 in __libc_start_main () at /usr/lib/libc.so.6
#25 0x000055f1eaf96ade in  ()
```

Arch Linux
swaylock 1.5-1
sway 1:1.6.1-1
wlroots 0.14.1-1

Based on the logs I can tell that swaylock crashes just as I come back to the device and not before. I believe this is related to monitors re-appearing. What leads to the crash is that I lock the screen and turn off the monitors. When I come back I turn on the monitors and press a key on the keyboard to wake up swayidle (which turns off the display outputs in software whereas I turn off the monitors with their physical buttons).

In that moment [waybar](https://github.com/Alexays/Waybar/) also crashes. None of the other several applications that are running crash. Some of them use wayand directly and some go through xwayland. waybar always crashes in this fashion but swaylock only sometimes.

I remember encountering this problem (swaylock and waybar crashing) in the past maybe half a year ago. I never reported it and the problem went away without me actively doing anything to fix it. Recently it has started again which is why I am reporting it now.

There is no hibernation or suspension happening which is why I do not think this is related to the other issues about crashes.

swayidle is run this way (not sure if relevant):
```
exec swayidle -w \
    timeout 7200 'swaylock -f -c 000000' \
    timeout 7210 'swaymsg "output * dpms off"' \
       resume 'swaymsg "output * dpms on"' \
    before-sleep 'swaylock -f -c 000000'
```

There is another monitor connected that is disabled through the sway config like `Output DP-1 disable`. Again not sure if relevant.

If you believe it would be helpful I am willing to build and run master with sanitizers. Note that I can only test this once a day because I have never encountered this problem without leaving the computer for several hours. Trying to reproduce by going through the same steps (lock screen, turn off monitors, wait a minute, press key on keyboard and turn on monitors) does not work even with the swayidle timeout set to a couple of seconds.

**Comment by emersion** [comment] 2021-07-30 07:30
Duplicate of https://github.com/swaywm/swaylock/issues/196#issuecomment-870688690

**Closed by emersion** 2021-07-30 07:30 UTC
