### ISSUE TITLE
Can't unlock swaylock.

### ISSUE THREAD

**Issue by trmendes** [swaywm/swaylock#51] opened 2019-02-11 23:11 UTC
I'm running the master version (12-02-19). I'm pretty sure I'm typing my password in the correct way and still swaylock won't let me unlock my screen.

```
2019-02-12 00:05:45 - [sway/commands/exec_always.c:46] Executing swaylock
2019-02-12 00:05:45 - [sway/commands/exec_always.c:87] Child process created with pid 9294
2019-02-12 00:05:45 - [sway/tree/root.c:253] Recording workspace for process 9294
2019-02-12 00:05:45 - [subprojects/wlroots/types/wlr_surface.c:595] New wlr_surface 0x55e7ceba42d0 (res 0x55e7ceb76ad0)
2019-02-12 00:05:45 - [subprojects/wlroots/types/wlr_layer_shell_v1.c:388] new layer_surface 0x55e7ceba45f0 (res 0x55e7ceb769b0)
2019-02-12 00:05:45 - [sway/desktop/layer_shell.c:365] new layer surface: namespace lockscreen layer 3 anchor 3 size 0x0 margin 0,0,0,0
2019-02-12 00:05:47 - [pam.c:102] pam_authenticate failed: invalid credentials
2019-02-12 00:05:49 - [GLES2] FS SIMD8 shader: 15 inst, 0 loops, 308 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 240 to 160 bytes.
2019-02-12 00:05:49 - [GLES2] FS SIMD16 shader: 15 inst, 0 loops, 322 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 240 to 160 bytes.
2019-02-12 00:05:50 - [pam.c:102] pam_authenticate failed: invalid credentials
```

I see it gives me "invalid credentials" but just like I said: I'm pretty sure there is nothing wrong with my typing. Any ideas?

**Comment by ianyfan** [comment] 2019-02-11 23:25
Duplicate of https://github.com/swaywm/sway/issues/3631

**Closed by ianyfan** 2019-02-11 23:25 UTC
