### ISSUE TITLE
Proposal: Provide a period of grace 

### ISSUE THREAD

**Issue by schauveau** [swaywm/swaylock#58] opened 2019-03-01 10:23 UTC

**Comment by emersion** [comment] 2019-03-01 10:24
Duplicate of https://github.com/swaywm/swaylock/issues/50

**Closed by emersion** 2019-03-01 10:24 UTC

**Comment by schauveau** [comment] 2019-03-01 10:26
The lockscreen can be annoying for example while watching a video. It would be nice to be able to delay the actual locking for a few seconds to give people the time to press a key or mouse their mouse.

**Comment by emersion** [comment] 2019-03-01 10:31
Yes. #50 suggests a way to do this.

**Comment by emersion** [comment] 2019-03-01 11:06
Question: how do people using i3 do this?

**Comment by schauveau** [comment] 2019-03-01 11:11
I don't know. Never used i3. 
A simple way is probably to kill the swaylock process from a resume event in swayidle.

**Comment by smlx** [comment] 2019-03-01 11:20
@emersion I use light-locker, which has an option to delay locking the screen.
https://manpages.debian.org/unstable/light-locker/light-locker.1.en.html

**Comment by emersion** [comment] 2019-03-01 12:40
Looks like a Wayland equivalent to this would be nice to have.

**Comment by emersion** [comment] 2023-01-11 10:07
This small client may be used to implement a grace period: https://git.sr.ht/~emersion/chayang

**Comment by bencollerson** [comment] 2023-03-06 06:21
Above mentioned, chayang is a much better way to implement a grace period. Keeping unnecessary complexity out of a screen locker is better for security anyway.
